//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.WebClientFactory.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.WebClientFactory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web site folder.
        /// </summary>
        internal static string AppliesToWebFolderReference {
            get {
                return ResourceManager.GetString("AppliesToWebFolderReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing action {0}.
        /// </summary>
        internal static string ExecutingAction {
            get {
                return ResourceManager.GetString("ExecutingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; already exists..
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid folder name..
        /// </summary>
        internal static string FolderNameIsNotValidMessage {
            get {
                return ResourceManager.GetString("FolderNameIsNotValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder is not valid.
        /// </summary>
        internal static string FolderNotExists {
            get {
                return ResourceManager.GetString("FolderNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Condition {0}/n{1}.
        /// </summary>
        internal static string InvalidConditionException {
            get {
                return ResourceManager.GetString("InvalidConditionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module folder on website is required.
        /// </summary>
        internal static string ModuleFolderNameOnWebSiteRequired {
            get {
                return ResourceManager.GetString("ModuleFolderNameOnWebSiteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module name must be a valid identifier.
        /// </summary>
        internal static string ModuleNameMustBeValidIdentifier {
            get {
                return ResourceManager.GetString("ModuleNameMustBeValidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module name cannot be empty.
        /// </summary>
        internal static string ModuleNameRequired {
            get {
                return ResourceManager.GetString("ModuleNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any project.
        /// </summary>
        internal static string ProjectReference {
            get {
                return ResourceManager.GetString("ProjectReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Actions... .
        /// </summary>
        internal static string StatusBarProgressMessage {
            get {
                return ResourceManager.GetString("StatusBarProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the dlls {0} are not present in the folder.
        /// </summary>
        internal static string SupportingLibrariesNotPresent {
            get {
                return ResourceManager.GetString("SupportingLibrariesNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template file not found..
        /// </summary>
        internal static string TemplateNotFoundMessage {
            get {
                return ResourceManager.GetString("TemplateNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid namespace is required.
        /// </summary>
        internal static string ValidNamespaceRequired {
            get {
                return ResourceManager.GetString("ValidNamespaceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View name must be a valid identifier.
        /// </summary>
        internal static string ViewNameMustBeValidIdentifier {
            get {
                return ResourceManager.GetString("ViewNameMustBeValidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View name cannot be empty.
        /// </summary>
        internal static string ViewNameRequired {
            get {
                return ResourceManager.GetString("ViewNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web folder {0} already exists..
        /// </summary>
        internal static string WebFolderAlreadyExists {
            get {
                return ResourceManager.GetString("WebFolderAlreadyExists", resourceCulture);
            }
        }
    }
}
