//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.CompositeWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.CompositeWeb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object builder has no strategies..
        /// </summary>
        internal static string BuilderHasNoStrategies {
            get {
                return ResourceManager.GetString("BuilderHasNoStrategies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Container cannot be added to itself..
        /// </summary>
        internal static string CannotAddContainerToItself {
            get {
                return ResourceManager.GetString("CannotAddContainerToItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create an instance of type &apos;{0}&apos;..
        /// </summary>
        internal static string CannotCreateInstanceOfType {
            get {
                return ResourceManager.GetString("CannotCreateInstanceOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclical dependency found while loading modules..
        /// </summary>
        internal static string CyclicDependencyFound {
            get {
                return ResourceManager.GetString("CyclicDependencyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add dependency for unknown module &apos;{0}&apos;; call AddModule() before AddDependency().
        /// </summary>
        internal static string DependencyForUnknownModule {
            get {
                return ResourceManager.GetString("DependencyForUnknownModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A module declared a dependency on another module which is not declared to be loaded. Missing module(s): {0}.
        /// </summary>
        internal static string DependencyOnMissingModule {
            get {
                return ResourceManager.GetString("DependencyOnMissingModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules with duplicated &apos;VirtualPath&apos; or &apos;AssemblyName&apos; were found: {0}.
        /// </summary>
        internal static string DuplicatedModuleLocationOrAssemblyName {
            get {
                return ResourceManager.GetString("DuplicatedModuleLocationOrAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object with this ID already exists: {0}..
        /// </summary>
        internal static string DuplicateID {
            get {
                return ResourceManager.GetString("DuplicateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A node with a duplicate key was added to the site map..
        /// </summary>
        internal static string DuplicateKeyExceptionMessage {
            get {
                return ResourceManager.GetString("DuplicateKeyExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service of this type already exists: {0}..
        /// </summary>
        internal static string DuplicateService {
            get {
                return ResourceManager.GetString("DuplicateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load module from assembly {0}. Error was:
        ///{1}.
        /// </summary>
        internal static string FailedToLoadModule {
            get {
                return ResourceManager.GetString("FailedToLoadModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpSessionState is not initialized..
        /// </summary>
        internal static string HttpSessionStateNotInitialized {
            get {
                return ResourceManager.GetString("HttpSessionStateNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the argument {0} provided for the enumeration {1} is invalid..
        /// </summary>
        internal static string InvalidEnumValue {
            get {
                return ResourceManager.GetString("InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing policy to build {0} named &apos;{1}&apos;..
        /// </summary>
        internal static string MissingPolicyNamed {
            get {
                return ResourceManager.GetString("MissingPolicyNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing policy to build unnamed {0}..
        /// </summary>
        internal static string MissingPolicyUnnamed {
            get {
                return ResourceManager.GetString("MissingPolicyUnnamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find an appropriately matching constructor..
        /// </summary>
        internal static string NoAppropriateConstructor {
            get {
                return ResourceManager.GetString("NoAppropriateConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Containers is not permitted. Use Container.Terminate or Container.Dispose to clean up a Container..
        /// </summary>
        internal static string NoRemoveContainerFromManagedObjectCollection {
            get {
                return ResourceManager.GetString("NoRemoveContainerFromManagedObjectCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided type {0} has not a static property {1}..
        /// </summary>
        internal static string ProviderDependencyPropertyNotFound {
            get {
                return ResourceManager.GetString("ProviderDependencyPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0}, required for component {1} is not available in the current context..
        /// </summary>
        internal static string ServiceMissingExceptionMessage {
            get {
                return ResourceManager.GetString("ServiceMissingExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} is not available in the current context..
        /// </summary>
        internal static string ServiceMissingExceptionSimpleMessage {
            get {
                return ResourceManager.GetString("ServiceMissingExceptionSimpleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __ROOT__.
        /// </summary>
        internal static string SiteMapRootNodeKey {
            get {
                return ResourceManager.GetString("SiteMapRootNodeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided String argument {0} must not be empty..
        /// </summary>
        internal static string StringCannotBeEmpty {
            get {
                return ResourceManager.GetString("StringCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided type {0} is not compatible with {1}..
        /// </summary>
        internal static string TypeNotCompatible {
            get {
                return ResourceManager.GetString("TypeNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you&apos;re trying to reach is unavailable..
        /// </summary>
        internal static string UserDoesntHaveAccessToTheRequestedResource {
            get {
                return ResourceManager.GetString("UserDoesntHaveAccessToTheRequestedResource", resourceCulture);
            }
        }
    }
}
