//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Orders.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderManagement.Orders.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string ApprovedStatusDescription {
            get {
                return ResourceManager.GetString("ApprovedStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        internal static string DraftStatusDescription {
            get {
                return ResourceManager.GetString("DraftStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sku cannot be empty.
        /// </summary>
        internal static string ErrorEmptySku {
            get {
                return ResourceManager.GetString("ErrorEmptySku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sku number entered is invalid.
        /// </summary>
        internal static string ErrorInvalidSku {
            get {
                return ResourceManager.GetString("ErrorInvalidSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sku number entered has already been used.
        /// </summary>
        internal static string ErrorRepeatedSku {
            get {
                return ResourceManager.GetString("ErrorRepeatedSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid querystring.
        /// </summary>
        internal static string InvalidQueryString {
            get {
                return ResourceManager.GetString("InvalidQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results were found..
        /// </summary>
        internal static string NoResultsFoundMessage {
            get {
                return ResourceManager.GetString("NoResultsFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method or operation is not implemented..
        /// </summary>
        internal static string NotImplementedExceptionMessage {
            get {
                return ResourceManager.GetString("NotImplementedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string RejectedStatusDescription {
            get {
                return ResourceManager.GetString("RejectedStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations. The current order has been submitted for approval with ID: {0}.
        /// </summary>
        internal static string SubmitConfirmationMessage {
            get {
                return ResourceManager.GetString("SubmitConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        internal static string SubmittedStatusDescription {
            get {
                return ResourceManager.GetString("SubmittedStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to submit the current order?.
        /// </summary>
        internal static string SubmittingOrderConfirmationMessage {
            get {
                return ResourceManager.GetString("SubmittingOrderConfirmationMessage", resourceCulture);
            }
        }
    }
}
